[package]
name = "cartesi-coprocessor-operator"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
advance_runner = {git = "https://github.com/zippiehq/cartesi-advance-runner", rev = "d56ca465282b258e6850fafb411926e90e9e7ff9"}
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
hex = "0.4"
serde_json = "1.0.107"
regex = "1.11.0"
dotenv = "0.15.0"

eigen-crypto-bls = { git = "https://github.com/Layr-Labs/eigensdk-rs", rev = "f69a9a943462f2a1635936ba5aa2f929ad718073", optional = true }
ark-serialize = "0.4.2"
sha2 = "0.10.8"
rs-car-ipfs = { git = "https://github.com/zippiehq/rs-car-ipfs" }
ipfs-api-backend-hyper = { version = "0.6.0", features = ["with-send-sync"], default-features = false }
futures = "0.3"
cid = "0.8.6"
alloy-primitives = "0.8.7"

[features]
default = []
bls_signing = [
    "eigen-crypto-bls",
]
